### ISSUE TITLE
Too many staabs

### ISSUE THREAD

**Issue by Aaron-Pool** [davestaab/staab-dashboard#1]
Lol needs less staabs

![lololololol](https://media1.tenor.com/images/1e6806d20555ae8f24d29e88c95bf75a/tenor.gif?itemid=9909884)

**Comment by davestaab** [comment]
Have you seen us? There's no end in sight 🐇 

We're live:
https://dashboard.staabstory.com

**Comment by davestaab** [comment]
It's my quarantine project with the fam.
